services:
  - type: web
    name: wartiqhelpchat
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: DISCORD_PUBLIC_KEY
        sync: false
      - key: LOG_LEVEL
        value: INFO
